const routes = {
  home: '/',
  productDetail: 'product/:slug',
  products: '/products/:slug',
  review: '/:slug/review',
  cart: '/cart',
  payment: '/cart/payment',
  paymentInfo: '/cart/payment-info',
  paymentResult: '/cart/payment-result',
  about: '/introduce',
  contact: '/lien-he',
  certificates: '/certificates',
  news: '/news/:slug',
  newsDetail: '/news/detail/:slug',
  login: '/login',
  register: '/register',
  profile: '/profile',
  member: '/member',
  memberOrder: '/member/order',
  memberOrderDetail: '/member/order/detail/:id',
  memberAccount: '/member/account/user-info',
  memberChangePassword: '/member/change-password',
  memberAddressInfo: '/member/account/user-info/address-info',
  memberUpdateAddress: '/member/account/user-info/address-info/update-address/:id',
  memberSocialAccount: '/member/social-account',
  memberPromotion: '/member/promotion',
  memberAccountSupport: '/member/account/support',
  notFound: '*',
};

export default routes;
